#all operations centrování/šířka sloupců
# #co jsou povinná pole a upravit pořadí, aby to sedělo potom všude        

        #POSTGRES ZAČÁTEK NA NOVÉM PC
        # sudo -u postgres psql
        # CREATE USER lalko_user WITH PASSWORD 'lalko_pass';
        # CREATE DATABASE lalko_db OWNER lalko_user;
        # GRANT ALL PRIVILEGES ON DATABASE lalko_db TO lalko_user;
        # \l (zjištění, že databáze existuje, vyjedu z toho kliknutím na "q")
        # připojení se k databázi pomocí \c lalko_db

        #RESET DATABÁZE
        # DROP DATABASE lalko_db;
        # CREATE DATABASE lalko_db;
        # python manage.py makemigrations; python manage.pymigrate;
        # python manage.py createsuperuser (tomashambalek@eu.aacoptics.com a uživatel a heslo "admin" pro superuser Django)
        # python manage.py load_input_data
        # python manage.py runserver
        
        #EXPORT PROJECT
        # pro requirements "pip freeze > requirements.txt"
        # pro export databáze "python manage.py dumpdata runlog.Operation > fixtures/operation_data.json"
        # git add .
        # git commit -m "První commit"
        # git push -u origin main

        #IMPORT PROJECT
        # jedno LALko: source venv/bin/activate
        # jedno LALko: git status; git pull origin main
        # dve LALka: pip install -r requirements.txt

        #POSTGRES IMPORT
        # sudo -u postgres psql
        # v Djangu - python manage.py migrate
        # v Djangu - python manage.py loaddata fixtures/initial_data.json
        # python manage.py runserver
        # python manage.py createsuperuser (tomashambalek@eu.aacoptics.com a uživatel a heslo "admin" pro superuser Django)
"""
Django settings for LALko project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(ov820_nvv880f31qzfa3g)8wqj99p*^1mrx=u2#!=$nib=qk6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'runlog',
    'django_tables2',
    'django_filters',
    'crispy_forms',
    'crispy_bootstrap4',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LALko.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LALko.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'lalko_db',
        'USER': 'lalko_user',
        'PASSWORD': 'lalko_pass',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/operations/'
LOGOUT_REDIRECT_URL = '/'

# Nastavení pro Django Crispy Forms
CRISPY_TEMPLATE_PACK = 'bootstrap4'