# Generated by Django 5.2.5 on 2025-08-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surface',
            options={'verbose_name': 'Surface', 'verbose_name_plural': 'Surfaces'},
        ),
        migrations.AlterField(
            model_name='operation',
            name='mold_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
