# Generated by Django 5.2.5 on 2025-08-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='department',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='user',
        ),
        migrations.AddField(
            model_name='operator',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
