# Generated by Django 5.2.5 on 2025-08-21 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='operators',
        ),
        migrations.AddField(
            model_name='operation',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='runlog.operator'),
        ),
    ]
