# Generated by Django 5.2.5 on 2025-08-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlog', '0002_remove_operation_operators_operation_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
