# Generated by Django 5.2.5 on 2025-08-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlog', '0002_remove_operator_department_remove_operator_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': 'Machine', 'verbose_name_plural': 'Machines'},
        ),
        migrations.AlterModelOptions(
            name='machiningtype',
            options={'verbose_name': 'Machining Type', 'verbose_name_plural': 'Machining Types'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'Operation', 'verbose_name_plural': 'Operations'},
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Operator', 'verbose_name_plural': 'Operators'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveField(
            model_name='operation',
            name='operator',
        ),
        migrations.AddField(
            model_name='operation',
            name='operators',
            field=models.ManyToManyField(related_name='operations', to='runlog.operator'),
        ),
    ]
