# Generated by Django 5.2.5 on 2025-08-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlog', '0003_changelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='operator',
        ),
        migrations.AddField(
            model_name='operation',
            name='operators',
            field=models.ManyToManyField(blank=True, to='runlog.operator', verbose_name='Operators'),
        ),
    ]
