# Generated by Django 5.2.5 on 2025-08-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlog', '0003_alter_operator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
